### ISSUE TITLE
don't cascade from lookup tables

### ISSUE THREAD

**Issue by tpolecat** [gemini-hlsw/gem#141]
I think we probably don't want rules like [this one](https://github.com/gemini-hlsw/gem/blob/master/modules/sql/src/main/resources/db/migration/V026__Ephemeris_Table.sql#L11) because it's not an ownership relationship. If you delete an element from an enum you will typically need to figure out how to migrate existing data rather than deleting it. What do you think about this?

**Comment by swalker2m** [comment]
Yes, that sounds right to me.  Cascading is done basically everywhere an enum is referenced so we'll need to make a lot of updates but it seems like the correct thing to do.
