### ISSUE TITLE
Use `text` instead of `character varying(n)`?

### ISSUE THREAD

**Issue by swalker2m** [gemini-hlsw/gem#175]
The schema employs many `varchar(n)` types.  I'm not sure what we're gaining by specifying an explicit limit.  According to the postgres doc, where the "three types" are

1) char(n) - blank padded with explicit limit
2) varchar(n) - explicit limit
3) varchar / text - no limit

> There is no performance difference among these three types, apart from increased storage space when using the blank-padded type, and a few extra CPU cycles to check the length when storing into a length-constrained column. While character(n) has performance advantages in some other database systems, there is no such advantage in PostgreSQL; in fact character(n) is usually the slowest of the three because of its additional storage costs and slower sorting. In most situations text or character varying should be used instead.

Suggest changing all `character varying(n)` to `text`.

**Comment by tpolecat** [comment]
This seems reasonable. 👍
