### ISSUE TITLE
Semester switchover time should delegate to ObservingNight

### ISSUE THREAD

**Issue by tpolecat** [gemini-hlsw/gem#251]
`Semester` [adds 10h to push the time into the next day if it falls after 2pm](https://github.com/gemini-hlsw/gem/blob/master/modules/core/shared/src/main/scala/gem/Semester.scala#L106), so we should probably make it delegate to `ObservingNight` for that information so the 2pm thing is only defined once.

See #250

**Comment by swalker2m** [comment]
Closed by #253.
