### ISSUE TITLE
Add Wavelength class

### ISSUE THREAD

**Issue by swalker2m** [gemini-hlsw/gem#81]
Central wavelength / observing wavelength / disperser lambda is specified in all instruments that do spectroscopy.  In the old OCS2 model, this is stored as a `double` with units of either μm or nm depending on the instrument.  After discussion with science, we believe that no instrument requires sub-angstrom wavelengths and so we would like to store wavelengths as an integral angstroms (10 angstroms = 1 nm = .001 μm).

Create a `Wavelength` type with a `toAngstroms: int` field, conversion to μm, nm, etc. Update GMOS to use `Wavelength`.

**Comment by tpolecat** [comment]
What's the largest wavelength we're likely to encounter? `Int` gets us a max of 214.7483647 millimeters, and `Long` gets us 922337.2036854775807 km.

**Comment by swalker2m** [comment]
Resolved by [#84](https://github.com/gemini-hlsw/gem/pull/84).
