### ISSUE TITLE
observations should not need to know the program they're in

### ISSUE THREAD

**Issue by tpolecat** [gemini-hlsw/gem#88]
In the construction [here](https://github.com/gemini-hlsw/gem/blob/master/modules/db/src/test/scala/gem/dao/StepDaoSpec.scala#L20-L47) we see that the program id is repeated in each observation, which is a potential consistency problem. There is also the opportunity for consistency issues with the indices, which must be unique.

So maybe something like

```scala

case class Observation[+S, +D](title: String, staticConfig: S, steps: List[D])

case class Program[+A](id: Program.Id, title: String, observations: Map[Int, A]) {
  def observationsWithIds: List[(Observation.Id, A)]
}

```

So if you need to know an observation's id you need to pass a pair around.

**Comment by swalker2m** [comment]
Also, if the Observation definitions do not include IDs they can be directly shared across libraries and multiple programs perhaps.

**Comment by swalker2m** [comment]
You weren't thinking this would extend down to the schema data model?  That would require a program/observation link table and make observation queries awkward I would think.
